version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VapidPublicKey=\"/ai-reminder/vapid-public-key\" VapidPrivateKey=\"/ai-reminder/vapid-private-key\" GroqApiKey=\"/ai-reminder/groq-api-key\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
